server:
  port: ${PORT:3306}
spring:
  datasource:
    url: ${mysql://root:vNkomLuhMNIxLxFiOlbwnPdNHQpCcyYI@mysql.railway.internal:3306/railway}
    username: ${root}
    password: ${vNkomLuhMNIxLxFiOlbwnPdNHQpCcyYI}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
